@startuml BI
hide methods

entity Sucursal {
    sucursal_id : bigint
    --
    sucursal_provincia : nvarchar(255)
    sucursal_localidad : nvarchar(255)
}

entity Cliente {
    cliente_id <<auto>>
    --
    cliente_minimo : int
    cliente_maximo : int
    cliente_rango : varchar(5)
}

entity Modelo {
    modelo_id : bigint
    --
    modelo_nombre : nvarchar(255)
}

entity Fecha {
    fecha_id <<auto>>
    --
    fecha_mes : int
    fecha_año : int
    fecha_cuatrimestre : int
}

entity Material {
    material_id <<auto>>
    --
    material_nombre
}

entity Turno {
    turno_id <<auto>>
    --
    turno_minimo_horas: int
    turno_minimo_minutos: int
    turno_maximo_horas: int
    turno_maximo_minutos: int
    turno_rango: varchar(13)
}

entity Localidad {
    localidad_id <<auto>>
    --
    localidad_nombre
    localidad_provincia
}

entity Estado {
    estado_id <<auto>>
    --
    estado_nombre nvarchar(255)
}

entity fact_table_factura {
    id_fecha <<FK>>
    id_sucursal <<FK>>
    id_modelo <<FK>>
    id_cliente <<FK>>
    --
    fact_numero : bigint
    fact_precio : decimal(18,2)
    fact_cantidad : decimal(18,0)
    fact_total : decimal(18,2)
}

entity fact_table_compra {
    id_fecha <<FK>>
    id_sucursal <<FK>>
    id_material <<FK>>
    --
    compra_numero : decimal(18,0)
    compra_precio : decimal(18,2)
    compra_cantidad : decimal(18,2)
    compra_total : decimal(18,2)
}

entity fact_table_pedido {
    id_fecha <<FK>>
    id_turno <<FK>>
    id_sucursal <<FK>>
    id_estado <<FK>>
    --
    cantidad_pedidos : int
}

entity fact_table_envio {
    id_fecha <<FK>>
    id_localidad <<FK>>
    --
	envio_numero : decimal(18,2),
	envio_fecha_programada datetime2(6),
	envio_fecha_entrega datetime2(6),
	envio_total decimal(18,2)
}

entity fact_table_fabricacion {
    id_fecha <<FK>>
    id_sucursal <<FK>>
    --
    fabricacion_tiempo_promedio : int
}


fact_table_factura --> Cliente
fact_table_factura --> Sucursal
Fecha <-- fact_table_factura
Modelo <-- fact_table_factura

Fecha <-- fact_table_compra
fact_table_compra --> Sucursal
fact_table_compra --> Material

fact_table_pedido --> Sucursal
fact_table_pedido --> Estado
Fecha <-- fact_table_pedido
Turno <-- fact_table_pedido

Fecha <-- fact_table_fabricacion
fact_table_fabricacion --> Sucursal

Fecha <-- fact_table_envio
Localidad <-- fact_table_envio

@enduml