@startuml BI
hide methods

entity Sucursal {
    sucursal_id : bigint
    --
    sucursal_provincia : varchar(50)
    sucursal_localidad : varchar(50)
}

entity Cliente {
    cliente_id <<auto>>
    --
    cliente_minimo : int
    cliente_maximo : int
    cliente_rango : varchar(5)
}

entity Modelo {
    modelo_id : bigint
    --
    modelo_nombre : varchar(50)
}

entity Fecha {
    fecha_id <<auto>>
    --
    fecha_mes : int
    fecha_año : int
    fecha_cuatrimestre : int
}

entity Factura {
    factura_id : bigint
}

entity Material {
    material_id <<auto>>
    --
    material_nombre
}

entity fact_table_facturas {
    id_fecha <<FK>>
    id_sucursal <<FK>>
    id_modelo <<FK>>
    id_cliente <<FK>>
    id_factura <<FK>>
    --
    fact_total
}

entity fact_table_compra {
    id_fecha <<FK>>
    id_sucursal <<FK>>
    id_material <<FK>>
    --
    compra_total
}

fact_table_facturas --> Cliente
fact_table_facturas --> Sucursal
Fecha <-- fact_table_facturas
Modelo <-- fact_table_facturas
fact_table_facturas --> Factura

Fecha <-- fact_table_compra
fact_table_compra --> Sucursal
fact_table_compra --> Material




@enduml