@startuml BI
hide methods

entity Fecha {
    fecha_id <<auto>>
    --
    fecha_mes : int
    fecha_año : int
    fecha_cuatrimestre : int
}

entity Cliente {
    cliente_id <<auto>>
    --
    cliente_minimo : int
    cliente_maximo : int
    cliente_rango : varchar(5)
}

entity Sucursal {
    sucursal_id : bigint
    --
    sucursal_provincia : nvarchar(255)
    sucursal_localidad : nvarchar(255)
}

entity Modelo {
    modelo_id : bigint
    --
    modelo_nombre : nvarchar(50)
}

entity Material {
    material_id <<auto>>
    --
    material_nombre : nvarchar(255)
}

entity Turno {
    turno_id <<auto>>
    --
    turno_minimo_horas: int
    turno_minimo_minutos: int
    turno_maximo_horas: int
    turno_maximo_minutos: int
    turno_rango: varchar(13)
}

entity Localidad {
    localidad_id <<auto>>
    --
    localidad_nombre : nvarchar(255)
    localidad_provincia : nvarchar(255)
}

entity Estado {
    estado_id <<auto>>
    --
    estado_nombre nvarchar(255)
}

together {

    entity fact_table_factura {
        id_fecha <<FK>>
        id_cliente <<FK>>
        id_sucursal <<FK>>
        id_modelo <<FK>>
        --
        fact_cantidad_facturas : decimal(18,0)
        fact_suma_total : decimal(18,2)
    }

    entity fact_table_modelo {
        id_fecha <<FK>>
        id_sucursal <<FK>>
        id_cliente <<FK>>
        id_modelo <<FK>>
        --
        modelo_cantidad : int
        modelo_total : decimal(18,2)
    }

    entity fact_table_envio {
        id_fecha <<FK>>
        id_localidad <<FK>>
        --
        envio_cantidad_envios : int
        envio_cumplidos : int
        envio_suma_costos : decimal(18,2)
    }

    entity fact_table_compra {
        id_fecha <<FK>>
        id_sucursal <<FK>>
        --
        compra_cantidad_compras DECIMAL(18,0)
        compra_suma_total DECIMAL(18,2)
    }

    entity fact_table_compra_material {
        id_fecha <<FK>>
        id_sucursal <<FK>>
        id_material <<FK>>
        --
        material_cantidad : int
        material_suma_total : decimal(18,2)
    }

    entity fact_table_pedido {
        id_fecha <<FK>>
        id_turno <<FK>>
        id_cliente <<FK>>
        id_sucursal <<FK>>
        id_estado <<FK>>
        --
        pedido_cantidad : bigint
    }

    entity fact_table_fabricacion {
        id_fecha <<FK>>
        id_sucursal <<FK>>
        --
        fabricacion_tiempo_promedio : int
    }

}


Fecha <-- fact_table_factura
fact_table_factura --> Cliente
fact_table_factura --> Sucursal
Modelo <-- fact_table_factura

fact_table_modelo --> Fecha
fact_table_modelo --> Sucursal
fact_table_modelo --> Cliente
fact_table_modelo --> Modelo

Fecha <-- fact_table_envio
Localidad <-- fact_table_envio

Fecha <-- fact_table_compra
fact_table_compra --> Sucursal
fact_table_compra --> Material

fact_table_compra_material --> Fecha
fact_table_compra_material --> Sucursal
fact_table_compra_material --> Material

Fecha <-- fact_table_pedido
Turno <-- fact_table_pedido
fact_table_pedido --> Cliente
fact_table_pedido --> Sucursal
fact_table_pedido --> Estado

Fecha <-- fact_table_fabricacion
fact_table_fabricacion --> Sucursal

@enduml