@startuml DER
!define ERD
hide methods

entity Sucursal{
+Sucursal_Nro
--
Sucursal_Domicilio
Sucursal_telefono
Sucursal_Mail
}

entity Domicilio{
+Domicilio_ID
--
Domicilio_Direccion
Domicilio_Localidad <<FK>>
}

entity Localidad{
+Localidad_ID
--
Localidad_Nombre
Localidad_Provincia <<FK>>
}

entity Provincia{
+Provincia_ID
--
Provincia_Nombre
}

entity Cliente{
+Cliente_Dni
--
Cliente_Domicilio
Cliente_Nombre
Cliente_Apellido
Cliente_Telefono
Cliente_FechaNacimiento
Cliente_Mail
}

entity Pedido{
+Pedido_Numero
--
Pedido_Sucursal <<FK>>
Pedido_Cliente <<FK>>
Pedido_Fecha
Pedido_Estado
}

entity Pedido_Detalle{
+Pedido_Numero <<FK>>
+Sillon_Modelo <<FK>>
--
Detalle_Pedido_Cantidad
Detalle_Pedido_Precio
Detalle_Pedido_Subtotal
}

entity Pedido_Cancelacion{
+Cancelacion_Pedido <<FK>>
--
Cancelacion_Fecha
Cancelacion_Motivo
}

entity Factura{
+Factura_Numero <<FK>>
--
Factura_Cliente <<FK>>
Factura_Sucursal <<FK>>
Factura_Pedido<<FK>>
Factura_Fecha
Factura_Total
}

entity Detalle_Factura{
+Detalle_Factura_Numero
+Detalle_Factura_Sillon
--
Detalle_Factura_Precio
Detalle_Factura_Cantidad
Detalle_Factura_SubTotal
}

entity Envio{
+Envio_Nro
--
Envio_Factura <<FK>>
Envio_Fecha_Programada
Envio_Fecha_Entrega
Envio_Importe_Translado
Envio_Importe_Subida
Envio_Total
}

entity Compra{
+Compra_Nro
--
Compra_Sucursal <<FK>>
Compra_Proveedor <<FK>>
Compra_Fecha
Compra_Total
}

entity Detalle_Compra{
+Compra_Nro <<FK>>
+Compra_Material <<FK>>
--
Compra_Precio
Compra_Cantidad
}

entity Proveedor{
+Proveedor_CUIT
--
Proveedor_Razon_Social
Proveedor_Domicilio
Proveedor_Telefono
Proveedor_Mail
}

entity Sillon{
+Sillon_Codigo
--
Sillon_Modelo<<FK>>
Sillon_Medida<<FK>>
Sillon Madera <<FK>>
Sillon_Tela <<FK>>
Sillon_Relleno <<FK>>
}

entity Modelo{
+Modelo_Codigo
--
Modelo_Nombre
Modelo_Descripcion
Modelo_Precio
}

entity Medida{
+Medida_ID
--
Medida_Alto
Medida_Ancho
Medida_Profundidad
Medida_Precio
}

entity Tela{
+Tela_ID <<FK>>
--
Tela_Color
Tela_Textura
Teña_Precio
}

entity Relleno{
+Relleno_ID <<FK>>
--
Relleno_Densidad
Relleno_Precio
}

entity Madera{
+Madera_ID <<FK>>
--
Madera_Color
Madera_Dureza
Madera_Precio
}

entity Material{
+Material_ID
--
Material_Tipo
}

Proveedor ||--o{ Compra
Compra ||--|{ Detalle_Compra
Sucursal ||--o{ Compra
Sucursal ||--o{ Pedido
Sucursal ||--o{ Factura
Pedido ||--|{ Pedido_Detalle
Cliente ||--o{ Pedido
Envio ||--|| Factura
Cliente ||--o{ Factura
Pedido||--o| Pedido_Cancelacion
Modelo ||--o{Sillon
Medida ||--o{Sillon
Tela ||--o{Sillon
Relleno ||--o{Sillon
Madera ||--o{Sillon
Sillon ||--o{ Pedido_Detalle
Sillon ||--o{ Detalle_Factura
Pedido ||--o| Factura
Factura ||--|{Detalle_Factura
Material ||--o{Detalle_Compra
Material -- Madera
Material -- Tela
Material -- Relleno
Localidad||--|{Domicilio
Provincia||--|{Localidad
Domicilio ||--o{Cliente
Domicilio ||--o{Proveedor
Domicilio ||--o{Sucursal
@enduml