USE GD1C2025
GO
DROP TABLE IF EXISTS DD.Detalle_Factura
DROP TABLE IF EXISTS DD.Envio
DROP TABLE IF EXISTS DD.Factura
DROP TABLE IF EXISTS DD.Detalle_Compra
DROP TABLE IF EXISTS DD.Cancelacion
DROP TABLE IF EXISTS DD.Detalle_Pedido
DROP TABLE IF EXISTS DD.Pedido
DROP TABLE IF EXISTS DD.Compra
DROP TABLE IF EXISTS DD.Sillon
DROP TABLE IF EXISTS DD.Modelo
DROP TABLE IF EXISTS DD.Madera
DROP TABLE IF EXISTS DD.Relleno
DROP TABLE IF EXISTS DD.Tela
DROP TABLE IF EXISTS DD.Material
DROP TABLE IF EXISTS DD.Medida
DROP TABLE IF EXISTS DD.Sucursal
DROP TABLE IF EXISTS DD.Proveedor
DROP TABLE IF EXISTS DD.Cliente
DROP TABLE IF EXISTS DD.Domicilio
DROP TABLE IF EXISTS DD.Localidad
DROP TABLE IF EXISTS DD.Provincia
DROP SCHEMA IF EXISTS DD
