USE GD1C2025
GO
DROP TABLE DD.Domicilio
DROP TABLE DD.Localidad
DROP TABLE DD.Provincia
DROP TABLE DD.Tela
DROP TABLE DD.Madera
DROP TABLE DD.Relleno
DROP TABLE DD.Material
DROP TABLE DD.Medida
DROP SCHEMA DD
